modules-search: [ local ]

sequence:
  - prepare:
      - welcome
      - locale
      - keyboard
      - partition
      - users
  - install:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - networkcfg
      - initramfs
      - grubcfg
      - bootloader
      - umount
  - postinstall:
      - finished

branding: default
prompt-at-end: true
